name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build-type: [ debug, release, release-shared ]
        exclude:
          - os: windows-latest
            build-type: release-shared


    steps:
      - uses: actions/checkout@v4

      - name: Configure with CMake
        run: cmake --preset ${{ matrix.build-type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build-type }} --parallel

 # On Windows shared builds, make sure the GKlib DLL is on PATH so tests can load it
      - name: Add shared‐lib directory to PATH
        if: runner.os == 'Windows' && matrix.build-type == 'release-shared'
        shell: powershell
        run: |
          $dllDir = Join-Path $PWD 'build/release-shared'
          Write-Host "Adding $dllDir to PATH"
          $Env:PATH = "$dllDir;$Env:PATH"

      - name: Test
        run: ctest --preset ${{ matrix.build-type }} --output-on-failure